eureka:
  client:
    service-url:
      default-zone=http: //localhost:8761/eureka/

spring:
  application:
    name: data-aggregator
  liquibase:
    change-log: classpath:db/changelog/liquibase-changeLog.xml
  jpa:
    hibernate:
      ddl-auto: none
      show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  datasource:
    url: jdbc:postgresql://localhost:5432/job_searcher_db
    username: postgres
    password: postgres
  rabbitmq:
    password: difficultPassword

server:
  port: 8081

---
spring:
  config:
    activate:
      on-profile:
        - PROD
  datasource:
    url: jdbc:postgresql://77.173.234.210:5432/job_searcher_db

---
spring:
  config:
    activate:
      on-profile:
        - TEST
  datasource:
    url: jdbc:h2:mem:testdb
    username: sa
    password:
    driverClassName: org.h2.Driver
    jpa:
      spring.jpa.database-platform: org.hibernate.dialect.H2Dialect
  h2:
    console.enabled: true